site_name: SixtyMeters - Smart Home
site_author: Theo Winter
site_url: https://sixtymeters.com
site_description: >-
  Building a Smart Home with Home Assistant and Node RED. Documentation & Tutorials of all things Smart Home.

repo_name: aerobless/SmartHome
repo_url: https://github.com/aerobless/SmartHome


nav:
  - Home: index.md
  - Hardware:
    - Overview: hardware/index.md
    - Computers: hardware/computers.md
    - Sensors: hardware/sensors.md
    - Power Switches: hardware/power-switches.md
    - Voice Assistants: hardware/voice-assistants.md
    - Lights: hardware/lights.md
    - Networking & Mesh: hardware/networking.md
    - TV & Entertainment: hardware/entertainment.md
    - Locks: hardware/locks.md
    - Blinds: hardware/blinds.md
    - NFC: hardware/nfc.md
    - Miscellaneous: hardware/miscellaneous.md
  - Software:
    - Home Assistant: software/home-assistant.md
    - KNX: software/knx/index.md
    - Node-RED: software/node-red/index.md
  - Automations: automations/index.md

theme:
  name: material
  language: en
  logo: './logo.svg'
  custom_dir: overrides
  features:
    - navigation.tabs
    - toc.integrate

extra:
  disqus: aerobless-smart-home
  social:
    - icon: fontawesome/brands/github-alt
      link: https://github.com/aerobless
    - icon: fontawesome/brands/twitter
      link: https://twitter.com/TheodorWinter

google_analytics:
  - UA-90728111-2
  - auto

markdown_extensions:
  - admonition
  - attr_list
  - footnotes
  - codehilite:
      guess_lang: false
  - toc:
      permalink: true
  - pymdownx.highlight
  - pymdownx.tabbed
  - pymdownx.superfences
  - pymdownx.details