site_name: Smart Home
site_author: Theo Winter
site_url: https://sixtymeters.com

repo_name: aerobless/SmartHome
repo_url: https://github.com/aerobless/SmartHome


nav:
  - Home: index.md
  - Hardware: hardware/index.md
  - Software:
    - Overview: software/overview.md
    - Home Assistant: software/home-assistant.md
    - KNX: software/knx/index.md
    - Node-RED: software/node-red/index.md
  - Automations: automations/index.md

theme:
  name: material
  language: en
  logo: './logo.svg'

extra:
  disqus: aerobless-smart-home
  social:
    - icon: fontawesome/brands/github-alt
      link: https://github.com/aerobless
    - icon: fontawesome/brands/twitter
      link: https://twitter.com/TheodorWinter

google_analytics:
  - UA-90728111-2
  - auto

markdown_extensions:
  - admonition
  - attr_list
  - codehilite:
      guess_lang: false
  - toc:
      permalink: true